beaytyProject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('beauty/', include('view_table.urls')),
    path('account/', include('django.contrib.auth.urls')),
]

view_table/urls.py
from django.urls import path
from . import views

app_name='view_table'
urlpatterns = [
    path('home/', views.home, name='home'),
    path('query_result/', views.query_result, name='query_result'),
    # path('upload/csv/', views.upload_csv, name='upload_csv'),
    path('view/', views.recommand_product, name='recommand_product'),
    path('trend/', views.trendView.as_view(), name='trend'),
    path('perfomance/', views.PerfomanceView.as_view(), name='perfomance'),
    
]

view_table/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models




class DataItem(models.Model):
    uid = models.TextField(blank=True,primary_key=True)
    pid = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'data_item'


class DataRating(models.Model):
    uid = models.TextField(blank=True, null=True)
    pid = models.TextField(blank=True, null=True)
    rating = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'data_rating'


class DataUser(models.Model):
    uid = models.TextField(blank=True, null=True)
    age = models.IntegerField(blank=True, null=True)
    sex = models.TextField(blank=True, null=True)
    job = models.TextField(blank=True, null=True)
    skintype = models.TextField(db_column='skinType', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'data_user'



class UxProduct(models.Model):
    id = models.TextField(blank=True, primary_key=True)
    brandname = models.TextField(db_column='brandName', blank=True, null=True)  # Field name made lowercase.
    colortype = models.TextField(db_column='colorType', blank=True, null=True)  # Field name made lowercase.
    companyname = models.TextField(db_column='companyName', blank=True, null=True)  # Field name made lowercase.
    hit = models.IntegerField(blank=True, null=True)
    image = models.TextField(blank=True, null=True)
    menutype = models.IntegerField(db_column='menuType', blank=True, null=True)  # Field name made lowercase.
    productname = models.TextField(db_column='productName', blank=True, null=True)  # Field name made lowercase.
    producttype = models.IntegerField(db_column='productType', blank=True, null=True)  # Field name made lowercase.
    skintype = models.TextField(db_column='skinType', blank=True, null=True)  # Field name made lowercase.
    gender = models.TextField(blank=True, null=True)
    statskintype = models.TextField(db_column='statSkinType', blank=True, null=True)  # Field name made lowercase.
    age = models.IntegerField(blank=True, null=True)
    job = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'ux_product'


class UxReview(models.Model):
    field_id = models.TextField(db_column='_id', blank=True, null=True)  # Field renamed because it started with '_'.
    content = models.TextField(blank=True, null=True)
    modifydate = models.TextField(db_column='modifyDate', blank=True, null=True)  # Field name made lowercase.
    point = models.IntegerField(blank=True, null=True)
    productidx = models.TextField(db_column='productIdx', blank=True, null=True)  # Field name made lowercase.
    regdate = models.TextField(db_column='regDate', blank=True, null=True)  # Field name made lowercase.
    semantic = models.IntegerField(blank=True, null=True)
    useridx = models.TextField(db_column='userIdx', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'ux_review'



class UxUser(models.Model):
    id = models.TextField(blank=True, primary_key=True)
    address = models.TextField(blank=True, null=True)
    addressdetail = models.TextField(db_column='addressDetail', blank=True, null=True)  # Field name made lowercase.
    age = models.IntegerField(blank=True, null=True)
    birthday = models.TextField(blank=True, null=True)
    email = models.TextField(blank=True, null=True)
    gender = models.TextField(blank=True, null=True)
    job = models.TextField(blank=True, null=True)
    lastlogindate = models.TextField(db_column='lastLoginDate', blank=True, null=True)  # Field name made lowercase.
    nickname = models.TextField(db_column='nickName', blank=True, null=True)  # Field name made lowercase.
    password = models.IntegerField(blank=True, null=True)
    regdate = models.TextField(db_column='regDate', blank=True, null=True)  # Field name made lowercase.
    skintype = models.TextField(db_column='skinType', blank=True, null=True)  # Field name made lowercase.
    x = models.IntegerField(blank=True, null=True)
    y = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'ux_user'

from django.contrib.auth.models import AbstractUser


class Customuser(AbstractUser): 
    age = models.IntegerField(blank=True, null=True)
    gender = models.TextField(blank=True, null=True)
    job = models.TextField(blank=True, null=True)
    nickname = models.TextField(db_column='nickName', blank=True, null=True)  # Field name made lowercase.
    skintype = models.TextField(db_column='skinType', blank=True, null=True)  # Field name made lowercase.


class RecommendedItem(models.Model):
    id = models.IntegerField(primary_key=True)
    uid = models.CharField(max_length=45)
    product = models.CharField(max_length=45)
    frequency = models.CharField(max_length=5)

    class Meta:
        managed = False
        db_table = 'recommended_item'

class Topk(models.Model):
    keyword = models.CharField(max_length=30, blank=True, primary_key=True)
    tfidf1 = models.FloatField(blank=True, null=True)
    tfidf2 = models.FloatField(blank=True, null=True)
    tfidf3 = models.FloatField(blank=True, null=True)
    tfidf4 = models.FloatField(blank=True, null=True)
    tfidf5 = models.FloatField(blank=True, null=True)
    rate = models.FloatField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'topk'

class TrendResult(models.Model):
    time = models.IntegerField(blank=True, primary_key=True)
    tweet = models.IntegerField(blank=True, null=True)
    beauty = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'trend_result'

view_table/views.py
from django.shortcuts import render,HttpResponseRedirect,reverse,get_object_or_404
from django.contrib.messages import error
import logging
from .models import UxProduct,UxUser,RecommendedItem,DataItem,UxProduct, Topk, TrendResult
from django.db.models import Q
from operator import itemgetter

from django.views.generic.edit import CreateView 
from django.views.generic import TemplateView,ListView

# from .forms import CreateUserForm

# Create your views here.


def home(request):

    return render(request,'view_table/home.html')

# class CreateUserView(CreateView): # generic view중에 CreateView를 상속받는다.
#     template_name = 'registration/signup.html' # 템플릿은?
#     # form_class =  CreateUserForm # 푸슨 폼 사용? >> 내장 회원가입 폼을 커스터마지징 한 것을 사용하는 경우
#     # form_class = UserCreationForm >> 내장 회원가입 폼 사용하는 경우
#     success_url = reverse_lazy('create_user_done') # 성공하면 어디로?

class RegisteredView(TemplateView): # generic view중에 TemplateView를 상속받는다.
    template_name = 'registration/signup_done.html' # 템플릿은?
    
class trendView(TemplateView): # generic view중에 TemplateView를 상속받는다.
    template_name = 'view_table/trend.html' # 템플릿은?
    def get_context_data(self, **kwargs):
        ctx =  super(trendView, self).get_context_data(**kwargs)
        # ctx['qna_form'] = QnaForm(initial={'post_pk':self.kwargs['pk']})
        topks = Topk.objects.all()
        ctx['rank1'] = topks[0]
        ctx['rank2'] = topks[1]
        ctx['rank3'] = topks[2]
        ctx['trend_result'] = TrendResult.objects.get(time=1)
        ctx['hot_topic'] = topks
        # print(ctx)
        return ctx

class PerfomanceView(TemplateView): # generic view중에 TemplateView를 상속받는다.
    template_name = 'view_table/perfomance.html' # 템플릿은?

def query_result(request):
    userID = "ObjectID(49)"
    
    recommend_product = RecommendedItem.objects.filter(uid=userID) #이름만 들어있음 product
    used_product = DataItem.objects.filter(uid="ObjectID(49)") #p.id로 접근
    used_p = list()
    used_p_name = list()
    for p in used_product:
        obj = UxProduct.objects.get(id=p.pid)
        used_p.append(obj) 
        used_p_name.append(obj.productname)
    recommend_product = list(recommend_product)
    recommend_total = recommend_product[:]
    for p in recommend_product:
        if p.product in used_p_name:
            recommend_total.remove(p)
    result = list()
    for r in recommend_total:
        print(r.product)
        result.append(UxProduct.objects.filter(productname=r.product)[0])
    
    
    return render(request,'view_table/query_result.html',{'recommend_product':recommend_product, 'used_product':used_p, 'recommmend_total1':result[0], 'recommmend_total2':result[1], 'recommmend_total3':result[2]})


def upload_csv(request):
    data = {}
    count = 0
    if "GET" == request.method:
        return render(request, "view_table/data_collection.html", data)
    # if not GET, then proceed
    try:
        csv_file = request.FILES["csv_file"]
        if not csv_file.name.endswith('.csv'):
            error(request,'File is not CSV type')
            return HttpResponseRedirect(reverse("view_table:home"))
        #if file is too large, return
        if csv_file.multiple_chunks():
            error(request,"Uploaded file is too big (%.2f MB)." % (csv_file.size/(1000*1000),))
            return HttpResponseRedirect(reverse("view_table:query_input"))

        file_data = csv_file.read().decode("utf-8")		

        lines = file_data.split("\n")
        print(lines)
        lines.remove('')
        
		#loop over the lines and save them in db. If error , store as string and then display
        for line in lines:						
            fields = line.split(",")
            data_dict = {}
            data_dict["name"] = fields[0]
            data_dict["start_date_time"] = fields[1]
            data_dict["end_date_time"] = fields[2]
            print(fields[0])# data_dict["notes"] = fields[3]
            count+=1
        return render(request,'view_table/status_information.html',{'count':count-1})
            # try:
            #     form = EventsForm(data_dict)
            #     if form.is_valid():
            #         form.save()					
            #     else:
            #         logging.getLogger("error_logger").error(form.errors.as_json())												
            # except Exception as e:
            #     logging.getLogger("error_logger").error(repr(e))					
            #     pass

    except Exception as e:
        logging.getLogger("error_logger").error("Unable to upload file. "+repr(e))
        error(request,"Unable to upload file. "+repr(e))

    return HttpResponseRedirect(reverse("view_table:query_input"))


def recommand_product(request): #user에 따라
    u1 = UxUser.objects.filter(nickname=request.GET["fulltext"]) #사용자
    product = list()
    product_dict = dict()
    for instance in u1:
        product = UxProduct.objects.all().filter(Q(skintype=instance.skintype)|Q(gender=instance.gender)|Q(job=instance.job))[:100]
        for i,p in enumerate(product):
            stack = 0
            if(p.skintype == instance.skintype):
                stack+=1
            if(p.gender == instance.gender):
                stack+=1
            if(p.job == instance.job):
                stack+=1
            # print(i,p.productname)
            product_dict.update({p.productname:stack})
            
    
    sdict=sorted(product_dict.items(),key=itemgetter(1),reverse=True)
    print('dict:',sdict)
    # product = UxProduct.objects.filter(brandname='라네즈')
    # print(product)
   
    # user = get_object_or_404(UxUser,field_id='ObjectId(5a9cf3b1a5440e033633f766)')
    # print(user.nickname)
    # for p in product:
    #     if(p.skintype==user.skintype):
    #         print('와!')

  
    return render(request,'view_table/query_result.html',{'product':product,})

view_table/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://unpkg.com/tailwindcss@1.0.4/dist/tailwind.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.2/css/bulma.min.css">
    <!-- <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> -->
    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/jumbotron/">
    <link href="/docs/4.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
    <style>
        /* Tab content - closed */
        .tab-content {
        max-height: 0;
        -webkit-transition: max-height .35s;
        -o-transition: max-height .35s;
        transition: max-height .35s;
        }
        /* :checked - resize to full height */
        .tab input:checked ~ .tab-content {
        max-height: 100vh;
        }
        /* Label formatting when open */
        .tab input:checked + label{
        /*@apply text-xl p-5 border-l-2 border-indigo-500 bg-gray-100 text-indigo*/
        font-size: 1.25rem; /*.text-xl*/
        padding: 1.25rem; /*.p-5*/
        border-left-width: 2px; /*.border-l-2*/
        border-color: #6574cd; /*.border-indigo*/
        background-color: #f8fafc; /*.bg-gray-100 */
        color: #6574cd; /*.text-indigo*/
        }
        /* Icon */
        .tab label::after {
        float:right;
        right: 0;
        top: 0;
        display: block;
        width: 1.5em;
        height: 1.5em;
        line-height: 1.5;
        font-size: 1.25rem;
        text-align: center;
        -webkit-transition: all .35s;
        -o-transition: all .35s;
        transition: all .35s;
        }
        /* Icon formatting - closed */
        .tab input[type=checkbox] + label::after {
        content: "+";
        font-weight:bold; /*.font-bold*/
        border-width: 1px; /*.border*/
        border-radius: 9999px; /*.rounded-full */
        border-color: #b8c2cc; /*.border-grey*/
        }
        .tab input[type=radio] + label::after {
        content: "\25BE";
        font-weight:bold; /*.font-bold*/
        border-width: 1px; /*.border*/
        border-radius: 9999px; /*.rounded-full */
        border-color: #b8c2cc; /*.border-grey*/
        }
        /* Icon formatting - open */
        .tab input[type=checkbox]:checked + label::after {
        transform: rotate(315deg);
        background-color: #6574cd; /*.bg-indigo*/
        color: #f8fafc; /*.text-grey-lightest*/
        }
        .tab input[type=radio]:checked + label::after {
        transform: rotateX(180deg);
        background-color: #6574cd; /*.bg-indigo*/
        color: #f8fafc; /*.text-grey-lightest*/
        }
     </style>
     <style>
			.carousel-open:checked + .carousel-item {
				position: static;
				opacity: 100;
			}
			.carousel-item {
				-webkit-transition: opacity 0.6s ease-out;
				transition: opacity 0.6s ease-out;
			}
			#carousel-1:checked ~ .control-1,
			#carousel-2:checked ~ .control-2,
			#carousel-3:checked ~ .control-3 {
				display: block;
			}
			.carousel-indicators {
				list-style: none;
				margin: 0;
				padding: 0;
				position: absolute;
				bottom: 2%;
				left: 0;
				right: 0;
				text-align: center;
				z-index: 10;
			}
			#carousel-1:checked ~ .control-1 ~ .carousel-indicators li:nth-child(1) .carousel-bullet,
			#carousel-2:checked ~ .control-2 ~ .carousel-indicators li:nth-child(2) .carousel-bullet,
			#carousel-3:checked ~ .control-3 ~ .carousel-indicators li:nth-child(3) .carousel-bullet {
				color: #2b6cb0;  /*Set to match the Tailwind colour you want the active one to be */
			}
		</style>
    {% load static %}
</head>
<body>
    <nav class="flex items-center justify-between flex-wrap bg-teal-500 ">
        <div class="flex items-center flex-shrink-0 text-white mr-6">
          <svg class="fill-current h-8 w-8 mr-2" width="54" height="54" viewBox="0 0 54 54" xmlns="http://www.w3.org/2000/svg"><path d="M13.5 22.1c1.8-7.2 6.3-10.8 13.5-10.8 10.8 0 12.15 8.1 17.55 9.45 3.6.9 6.75-.45 9.45-4.05-1.8 7.2-6.3 10.8-13.5 10.8-10.8 0-12.15-8.1-17.55-9.45-3.6-.9-6.75.45-9.45 4.05zM0 38.3c1.8-7.2 6.3-10.8 13.5-10.8 10.8 0 12.15 8.1 17.55 9.45 3.6.9 6.75-.45 9.45-4.05-1.8 7.2-6.3 10.8-13.5 10.8-10.8 0-12.15-8.1-17.55-9.45-3.6-.9-6.75.45-9.45 4.05z"/></svg>
          <span class="font-semibold text-4xl tracking-tight">recommend</span>
          <a href=""></a>
        </div>
        
        <div class="w-full block flex-grow lg:flex lg:items-center lg:w-auto" style="margin-top: 20px;" >
          <div class="text-3xl lg:flex-grow">
            <a href="{% url 'view_table:home' %}" class="block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white mr-4">
              home
            </a>
            <a href="{% url 'view_table:query_result' %}" class="block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white mr-4">
              recommendation
            </a>
            <a href="{% url 'view_table:trend' %}" class="block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white mr-4">
              trend
            </a>
            <a href="{% url 'view_table:perfomance' %}" class="block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white mr-4">
                성능평가
              </a>
            {% if user.is_active %}
              <a href="{%url 'logout' %}" class="block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white">
                logout
              </a>
            {% else %}
              <a href="{%url 'login' %}" class="block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white">
                login
              </a>
              <a href="" class="block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white">
                signup
              </a>
            {% endif %}
          </div>
        </div>
      </nav>
    
   {% block content %}
   {% endblock %}
</body>
<script>
    /* Optional Javascript to close the radio button version by clicking it again */
    var myRadios = document.getElementsByName('tabs2');
    var setCheck;
    var x = 0;
    for(x = 0; x < myRadios.length; x++){
        myRadios[x].onclick = function(){
            if(setCheck != this){
                 setCheck = this;
            }else{
                this.checked = false;
                setCheck = null;
        }
        };
    }
 </script>
</html>